#---
- name: Configure Network
  hosts: nodes
  become: yes
  vars:
    ssh_config_host_configs:
    - host: "*"
      StrictHostKeyChecking: "no"
      UserKnownHostsFile: "/dev/null"

  tasks:
    - name: Configure hosts
      template:
          src: "etc/hosts.j2"
          dest: "/etc/hosts"
          owner: root
          group: root
          mode: 0644
          unsafe_writes: yes

  roles:
    - role: ansible-ssh-config
